Added shell sort and big integer
vivekcrux/Data-Structures-and-Algorithms pull request #10
Opened 2021-10-24 15:15 UTC by RohanGoyal2014

2021-10-24 15:16 UTC, shubhamg931 approved these changes
Rejected

2021-10-24 15:20 UTC, shubhamg931 requested changes
Please close this PR, and follow hacktoberfest best practices. Such PRs does not maintain the decorum of the event

2021-10-24 15:21 UTC, shubhamg931 commented on shellSort.cpp
> +  shell_sort(a,n);
Why not use sort() function only instead, this is not acceptable

2021-10-24 18:07 UTC, RohanGoyal2014 commented on shellSort.cpp
> +  shell_sort(a,n);
Change internal implementation of sort method to use shell sort and then I can do that. Meanwhile resolving this conversation. Awaiting your PR on GNU''s repo which changes sort() method's implementation. ☺️

2021-10-24 18:41 UTC, merged

2021-10-25 05:08 UTC, shubhamg931 commented on shellSort.cpp
> +  shell_sort(a,n);
That is just stupid, what are we achieving by wasting efforts on writing our own shell sort here. Where are you using this, please don't make foolish arguments

2021-10-25 05:17 UTC, RohanGoyal2014 commented on shellSort.cpp
> +  shell_sort(a,n);
Seems like you are unable to raise a PR for this. No worries. I understand you can't ☺️

2021-10-25 05:21 UTC, shubhamg931 commented on shellSort.cpp
> +  shell_sort(a,n);
Why would someone just add a sorting algorithm like this for no reason? At least mention the use case for adding this and some better documentation around it as to why are we using this. This seems like an effort to win hacktoberfest T-shirt, one should not make a habit of such things

Hope you understand :)